export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const GET_TASKS_BY_ID_REQUEST = 'GET_TASKS_BY_ID_REQUEST';
export const GET_TASKS_BY_ID_SUCCESS = 'GET_TASKS_BY_ID_SUCCESS';
export const GET_TASKS_BY_ID_ERROR = 'GET_TASKS_BY_ID_ERROR';

export const CREATE_TASKS_REQUEST = 'CREATE_TASKS_REQUEST';
export const CREATE_TASKS_SUCCESS = 'CREATE_TASKS_SUCCESS';
export const CREATE_TASKS_ERROR = 'CREATE_TASKS_ERROR';

export const DELETE_TASKS_REQUEST = 'DELETE_TASKS_REQUEST';
export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS';
export const DELETE_TASKS_ERROR = 'DELETE_TASKS_ERROR';
